package calculator.core;

public enum InputStatus {
    EXIT, HELP, SKIP, UNKNOWN_COMMAND, INVALID_EXPRESSION, INVALID_IDENTIFIER, INVALID_ASSIGNMENT, UNKNOWN_VARIABLE, VARIABLE_VALUE, ASSIGNMENT, EXPRESSION
}
